aset/urls.py
from django.urls import path

from .views import *

app_name = 'aset'

urlpatterns = [
    path('listaset', listaset, name='listaset'),
    path('buataset', buataset, name='buataset'),

    path('listaset_dekorasi', listaset_dekorasi, name='listaset_dekorasi'),
    path('listaset_bibittanaman', listaset_bibittanaman, name='listaset_bibittanaman'),
    path('listaset_kandang', listaset_kandang, name='listaset_kandang'),
    path('listaset_hewan', listaset_hewan, name='listaset_hewan'),
    path('listaset_alatproduksi', listaset_alatproduksi, name='listaset_alatproduksi'),
    path('listaset_petaksawah', listaset_petaksawah, name='listaset_petaksawah'),

    path('buatasetdekorasi', buatasetdekorasi, name='buasetasetdekorasi'),
    path('buatasetbibittanaman', buatasetbibittanaman, name='buatasetbibittanaman'),
    path('buatasetkandang', buatasetkandang, name='buatasetkandang'),
    path('buatasethewan', buatasethewan, name='buatasethewan'),
    path('buatasetalatproduksi', buatasetalatproduksi, name='buatasetalatproduksi'),
    path('buatasetpetaksawah', buatasetpetaksawah, name='buatasetpetaksawah')
]

hi_day_b06/urls.py
from django.contrib import admin
from login_register.views import login as index
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login_register/', include('login_register.urls')),
    path('home/', include('home.urls')),
    path('produk/', include('produk.urls')),
    path('histori_produksi/', include('histori_produksi.urls')),
    path('paketkoin/', include('paketkoin.urls')),
    path('transaksipembeliankoin/', include('transaksipembeliankoin.urls')),
    path('transaksiupgradelumbung/', include('transaksiupgradelumbung.urls')),
    path('lumbung/', include('lumbung.urls')),
    path('historitanaman/', include('historitanaman.urls')),
    path('aset/', include('aset.urls')),
    path('koleksiaset/', include('koleksiaset.urls')),
    path('transaksipembelianaset/', include('transaksipembelianaset.urls')),
    re_path(r'^$', index, name='index'),
]

historitanaman/urls.py
from django.urls import path

from .views import *
from home.views import home

app_name = 'historitanaman'

urlpatterns = [
    path('home', home, name='home'),
    path('createhistoritanamanpengguna', createhistoritanamanpengguna, name='createhistoritanamanpengguna'),
    path('readhistoritanamanadmin', readhistoritanamanadmin, name='readhistoritanamanadmin'),
    path('readhistoritanamanpengguna', readhistoritanamanpengguna, name='readhistoritanamanpengguna'),
]

historitanaman/forms.py
from django.contrib.auth import forms
from django.forms import ModelForm, fields
from django import forms
from django.utils import timezone
from django.db import models
import datetime
from django.db.models.deletion import DO_NOTHING
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
# from . import models 

class CreateHistoriTanamanPenggunaForm(forms.Form):
    bibit_tanaman = forms.CharField(label='Bibit Tanaman')
    jumlah = forms.CharField(label='Jumlah')
    xp = forms.CharField(label='XP')
    waktu_awal = models.DateTimeField(auto_now_add=True)
    waktu_selesai = waktu_awal

historitanaman/views.py
import email
from collections import namedtuple
import imp
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.db import connection
from django.db.utils import IntegrityError, InterfaceError
from .forms import *
from django.utils import timezone

# Create your views here.
def namedtuplefetchall(cursor):
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def createhistoritanamanpengguna(request):
    # form = CreateHistoriTanamanPenggunaForm(request.POST or None)
    cursor = connection.cursor()
    cursor.execute("SET search_path TO public")
    userEmail = request.session ['email']
    cursor.execute("SET SEARCH_PATH TO hidayb06")
    cursor.execute("SELECT * FROM PRODUK WHERE PRODUK.ID IN (SELECT * FROM HASIL_PANEN)")
    result = cursor.fetchall()
    response = {}
    response['hasil_panen'] = []
    now = timezone.now()
    for i in range(len(result)):
        response['hasil_panen'].append([
            result[i][0], result[i][1]
        ])
    if (request.method == 'POST'):
        # bibit = form.cleaned_data['bibit_tanaman']
        # jumlah = form.cleaned_data['jumlah']
        # xp = form.cleaned_data['xp']
        # waktu_awal = form.cleaned_data['waktu_awal']
        # waktu_selesai = form.cleaned_data['waktu_selesai']
        if (request.POST['id_bibit_tanaman'] == "" or request.POST['jumlah'] == "" or request.POST['xp'] == ""):
            message = "Masih ada yang kosong"
            return render(request, 'historitanaman/createHistoriTanamanPengguna.html', {'message':message})
        else:
            try:
                cursor.execute("INSERT INTO HISTORI_TANAMAN (email,waktu_awal,id_bibit_tanaman) VALUES (%s,%s, (SELECT BIBIT_TANAMAN_MENGHASILKAN_HASIL_PANEN.ID_BIBIT_TANAMAN FROM BIBIT_TANAMAN_MENGHASILKAN_HASIL_PANEN, PRODUK WHERE PRODUK.ID = BIBIT_TANAMAN_MENGHASILKAN_HASIL_PANEN.ID_HASIL_PANEN AND PRODUK.NAMA = %s))", [userEmail,now,request.POST['id_bibit_tanaman']])
                cursor.execute("INSERT INTO HISTORI_PRODUKSI (email,waktu_awal,waktu_selesai,jumlah,xp) VALUES (%s,%s,%s,%d,%d)", [userEmail,now,now,request.POST['jumlah'],request.POST['xp']])
                return redirect("/historitanaman/readhistoritanamanpengguna")
            except Exception as error:
                print(error)
    return render(request, 'historitanaman/createHistoriTanamanPengguna.html', response)

def readhistoritanamanadmin(request):
    cursor = connection.cursor()
    cursor.execute("SET search_path TO public")
    role = request.session ['role']
    userEmail = request.session['email']
    if (role == "admin"):
        try:
            cursor.execute("SET SEARCH_PATH TO hidayb06")
            cursor.execute("""SELECT HISTORI_TANAMAN.EMAIL, HISTORI_TANAMAN.WAKTU_AWAL, HISTORI_PRODUKSI.WAKTU_SELESAI, HISTORI_PRODUKSI.JUMLAH, HISTORI_PRODUKSI.XP, PETAK_SAWAH.JENIS_TANAMAN FROM (HISTORI_TANAMAN NATURAL JOIN HISTORI_PRODUKSI), BIBIT_TANAMAN_DITANAM_DI_PETAK_SAWAH, PETAK_SAWAH WHERE HISTORI_TANAMAN.ID_BIBIT_TANAMAN = BIBIT_TANAMAN_DITANAM_DI_PETAK_SAWAH.ID_BIBIT_TANAMAN AND BIBIT_TANAMAN_DITANAM_DI_PETAK_SAWAH.ID_PETAK_SAWAH = PETAK_SAWAH.ID_ASET AND HISTORI_TANAMAN.EMAIL IN (SELECT PENGGUNA.EMAIL FROM PENGGUNA);""")
            result = namedtuplefetchall(cursor)
        except Exception as e:
            print(e)

        return render(request, 'historitanaman/readHistoriTanamanAdmin.html', {'result':result})

def readhistoritanamanpengguna(request):
    cursor = connection.cursor()
    cursor.execute("SET search_path TO public")
    role = request.session ['role']
    userEmail = request.session['email']
    if (role == "pengguna"):
        try:
            cursor.execute("SET SEARCH_PATH TO hidayb06")
            cursor.execute("""SELECT HISTORI_TANAMAN.WAKTU_AWAL, HISTORI_PRODUKSI.WAKTU_SELESAI, HISTORI_PRODUKSI.JUMLAH, HISTORI_PRODUKSI.XP, PETAK_SAWAH.JENIS_TANAMAN FROM (HISTORI_TANAMAN NATURAL JOIN HISTORI_PRODUKSI), BIBIT_TANAMAN_DITANAM_DI_PETAK_SAWAH, PETAK_SAWAH WHERE HISTORI_TANAMAN.ID_BIBIT_TANAMAN = BIBIT_TANAMAN_DITANAM_DI_PETAK_SAWAH.ID_BIBIT_TANAMAN AND BIBIT_TANAMAN_DITANAM_DI_PETAK_SAWAH.ID_PETAK_SAWAH = PETAK_SAWAH.ID_ASET AND HISTORI_TANAMAN.EMAIL = %s;""", [userEmail])
            result = namedtuplefetchall(cursor)
        except Exception as e:
            print(e)

        return render(request, 'historitanaman/readHistoriTanamanPengguna.html', {'result':result})

historitanaman/templates/historitanaman/createHistoriTanamanPengguna.html
{% extends "home/basePengguna.html" %}
{% load static %}

{% block head %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>Create Histori Tanaman (Pengguna)</title>
{% endblock head %}

{% block content %}
<form action="/historitanaman/createhistoritanamanpengguna" method="POST">
  {% csrf_token %}
<h1>FORM PRODUKSI TANAMAN (PENGGUNA)</h1>
<p>Bibit Tanaman</p>
<select name="id_bibit_tanaman">
    {% for id, jenis_tanaman in hasil_panen %}
    <option value={{id}}>{{jenis_tanaman}}</option>
    {% endfor %}
  </select>
<p>Jumlah</p>
<input id="jumlah" type="number" name="jumlah" onchange="adderxp()" min="0">
<p>XP</p>
<input id="xp" type="number" name="xp" readonly="readonly" value = "0">
<br>
<p style="color: red;">{{ message }}</p>
<input type = "submit" value = "submit"/>
<p><a href="{% url 'historitanaman:readhistoritanamanpengguna' %}">Cancel</a></p>
</form>
<script>
  function adderxp() {
    const jumlah = document.getElementById("jumlah").value
    document.getElementById("xp").value = jumlah*5
  }
</script>
{% endblock content %}

historitanaman/templates/historitanaman/readHistoriTanamanAdmin.html
{% extends "home/baseAdmin.html" %}
{% load static %}

{% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Read Histori Tanaman (Admin)</title>
{% endblock head %}
    
{% block content %}
<div class="container-md">
    <div class="d-grip gap-3">
        <div class="p-2 bg-light border">
            <div class="mx-auto" style="width: 500px;">
                <h1>List Histori Tanaman (Admin)</h1>
            </div>
        </div>
        <div class="p-2 bg-light border">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col"><b>No</b></th>
                        <th scope="col"><b>Email Pengguna</b></th>
                        <th scope="col"><b>Waktu Awal</b></th>
                        <th scope="col"><b>Waktu Selesai</b></th>
                        <th scope="col"><b>Jumlah</b></th>
                        <th scope="col"><b>XP</b></th>
                        <th scope="col"><b>Bibit Tanaman</b></th>
                    </tr>
                </thead>
                <tbody>
                    {% for res in result %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ res.email }}</td>
                        <td>{{ res.waktu_awal }}</td>
                        <td>{{ res.waktu_selesai }}</td>
                        <td>{{ res.jumlah }}</td>
                        <td>{{ res.xp }}</td>
                        <td>{{ res.jenis_tanaman }}</td>
                    </tr>
                    {% endfor %}
                  <tr>
                  </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

historitanaman/templates/historitanaman/readHistoriTanamanPengguna.html
{% extends "home/basePengguna.html" %}
{% load static %}

{% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Read Histori Tanaman (Pengguna)</title>
{% endblock head %}
    
{% block content %}
<div class="container-md">
    <div class="d-grip gap-3">
        <div class="p-2 bg-light border">
            <div class="mx-auto" style="width: 500px;">
                <h1>List Histori Tanaman (Pengguna)</h1>
            </div>
        </div>
        <div class="p-2 bg-light border">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col"><b>No</b></th>
                        <th scope="col"><b>Waktu Awal</b></th>
                        <th scope="col"><b>Waktu Selesai</b></th>
                        <th scope="col"><b>Jumlah</b></th>
                        <th scope="col"><b>XP</b></th>
                        <th scope="col"><b>Bibit Tanaman</b></th>
                    </tr>
                </thead>
                <tbody>
                    {% for res in result %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ res.waktu_awal }}</td>
                        <td>{{ res.waktu_selesai }}</td>
                        <td>{{ res.jumlah }}</td>
                        <td>{{ res.xp }}</td>
                        <td>{{ res.jenis_tanaman }}</td>
                    </tr>
                    {% endfor %}
                  <tr>
                  </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}