aset/urls.py
from django.urls import path

from .views import *

app_name = 'aset'

urlpatterns = [
    path('listaset', listaset, name='listaset'),
    path('buataset', buataset, name='buataset'),

    path('listaset_dekorasi', listaset_dekorasi, name='listaset_dekorasi'),
    path('listaset_bibittanaman', listaset_bibittanaman, name='listaset_bibittanaman'),
    path('listaset_kandang', listaset_kandang, name='listaset_kandang'),
    path('listaset_hewan', listaset_hewan, name='listaset_hewan'),
    path('listaset_alatproduksi', listaset_alatproduksi, name='listaset_alatproduksi'),
    path('listaset_petaksawah', listaset_petaksawah, name='listaset_petaksawah'),

    path('buatasetdekorasi', buatasetdekorasi, name='buasetasetdekorasi'),
    path('buatasetbibittanaman', buatasetbibittanaman, name='buatasetbibittanaman'),
    path('buatasetkandang', buatasetkandang, name='buatasetkandang'),
    path('buatasethewan', buatasethewan, name='buatasethewan'),
    path('buatasetalatproduksi', buatasetalatproduksi, name='buatasetalatproduksi'),
    path('buatasetpetaksawah', buatasetpetaksawah, name='buatasetpetaksawah')
]

hi_day_b06/urls.py
from django.contrib import admin
from login_register.views import login as index
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login_register/', include('login_register.urls')),
    path('home/', include('home.urls')),
    path('produk/', include('produk.urls')),
    path('histori_produksi/', include('histori_produksi.urls')),
    path('paketkoin/', include('paketkoin.urls')),
    path('transaksipembeliankoin/', include('transaksipembeliankoin.urls')),
    path('transaksiupgradelumbung/', include('transaksiupgradelumbung.urls')),
    path('lumbung/', include('lumbung.urls')),
    path('historitanaman/', include('historitanaman.urls')),
    path('aset/', include('aset.urls')),
    path('koleksiaset/', include('koleksiaset.urls')),
    path('transaksipembelianaset/', include('transaksipembelianaset.urls')),
    re_path(r'^$', index, name='index'),
]

home/urls.py
from django.urls import path

from .views import *

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('logout', logout, name='logout'),
]

login_register/urls.py
from django.urls import path

from .views import *

app_name = 'login_register'

urlpatterns = [
    path('login', login, name='login'),
    path('registeradmin', registeradmin, name='registeradmin'),
    path('registerpengguna', registerpengguna, name='registerpengguna'),
]

home/views.py
import email
import imp
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.db import connection
from collections import namedtuple
from django.db.utils import IntegrityError, InterfaceError

# Create your views here.
def namedtuplefetchall(cursor):
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def home(request):
    cursor = connection.cursor()
    cursor.execute("SET search_path TO public")
    if request.session.has_key('email'):
        role = request.session ['role']
        email = request.session ['email']
        if (role == "pengguna"):
            try:
                cursor.execute("SET SEARCH_PATH TO hidayb06")
                cursor.execute("SELECT * FROM pengguna WHERE email = %s", [email])
                result = namedtuplefetchall(cursor)
            except Exception as e:
                print(e)
            return render (request, 'home/homePengguna.html', {'result': result})
        elif (role == "admin"):
            try:
                cursor.execute("SET SEARCH_PATH TO hidayb06")
                cursor.execute("SELECT * FROM admin WHERE email = %s", [email])
                result = namedtuplefetchall(cursor)
            except Exception as e:
                print(e)
            return render (request, 'home/homeAdmin.html', {'result': result})
    else:
        return redirect('login_register')

def logout(request):
    try:
        del request.session['email']
        del request.session['role']
    except:
        pass
    return redirect('/login_register/login')

home/templates/home/baseAdmin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% block meta %}{% endblock meta %}
</head>
<body>
  
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container-fluid">
        <a href="/home" class="navbar-brand">HI-DAY B06</a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarCollapse" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Lumbung</a>
              <div class="dropdown-menu">
                <a href="/lumbung/readlumbung" class="dropdown-item">Lihat Isi Lumbung</a>
                <a href="/transaksiupgradelumbung/readtransaksiupgradelumbungadmin" class="dropdown-item">List Transaksi Upgrade Lumbung</a>
              </div>
            </li>
          </ul>
            <ul class="nav navbar-nav">
              <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Paket Koin</a>
                <div class="dropdown-menu">
                    <a href="/paketkoin/createpaketkoinadmin" class="dropdown-item">Buat Paket Koin</a>
                    <a href="/paketkoin/readpaketkoinadmin" class="dropdown-item">List Paket Koin</a>
                    <a href="/transaksipembeliankoin/readtransaksipembeliankoinadmin" class="dropdown-item">List Transaksi Pembelian Koin</a>
                </div>
              </li>
            </ul>
            <ul class="nav navbar-nav">
                <li class="nav-item dropdown">
                  <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Aset</a>
                  <div class="dropdown-menu">
                      <a href="/aset/buataset" class="dropdown-item">Buat Aset</a>
                      <a href="/aset/listaset" class="dropdown-item">List Aset</a>
                      <a href="" class="dropdown-item">Buat Hewan Menghasilkan Produk Hewan</a>
                      <a href="" class="dropdown-item">List Hewan Menghasilkan Produk Hewan</a>
                      <a href="" class="dropdown-item">Buat Bibit Menghasilkan Panen</a>
                      <a href="" class="dropdown-item">List Bibit Menghasilkan Panen</a>
                  </div>
                </li>
            </ul>
            <ul class="nav navbar-nav">
              <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Koleksi Aset</a>
                <div class="dropdown-menu">
                    <a href="/koleksiaset/listkoleksi" class="dropdown-item">List Koleksi Aset</a>
                    <a href="/transaksipembelianaset/listtransaksi" class="dropdown-item">List Transaksi Pembelian Aset</a>
                </div>
              </li>
          </ul>
          <ul class="nav navbar-nav">
            <li class="nav-item dropdown">
              <a href="/produk" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Produk</a>
              <div class="dropdown-menu">
                  <a href="/produk/buatproduk" class="dropdown-item">Buat Produk</a>
                  <a href="/produk/listproduk" class="dropdown-item">List Produk</a>
                  <a href="/produk/buatproduksi" class="dropdown-item">Buat Produksi</a>
                  <a href="/produk/listproduksi" class="dropdown-item">List Produksi</a>
              </div>
            </li>
          </ul>
          <ul class="nav navbar-nav">
            <li class="nav-item dropdown">
              <a href="/histori_produksi" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Histori Produksi</a>
              <div class="dropdown-menu">
                  <a href="" class="dropdown-item">List Histori Produksi Hewan</a>
                  <a href="/historitanaman/readhistoritanamanadmin" class="dropdown-item">List Histori Produksi Tanaman</a>
                  <a href="/histori_produksi/historiprodukmakanan" class="dropdown-item">List Histori Produksi Makanan</a>
              </div>
            </li>
          </ul>
          <ul class="nav navbar-nav">
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pesanan</a>
              <div class="dropdown-menu">
                  <a href="" class="dropdown-item">Buat Pesanan</a>
                  <a href="" class="dropdown-item">List Pesanan</a>
                  <a href="" class="dropdown-item">List Histori Penjualan</a>
              </div>
            </li>
          </ul>
            <ul class="nav navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Akun</a>
                    <div class="dropdown-menu dropdown-menu-end">
                        <a href="/home/logout" class="dropdown-item">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="mainbox container-fluid">
    {% block content %}

    {% endblock content %}
  </div>
  {% block scriptTambahan %}

{% endblock scriptTambahan %}
</body>

</html>

home/templates/home/basePengguna.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% block meta %}{% endblock meta %}
</head>
<body>
  
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container-fluid">
        <a href="/home" class="navbar-brand">HI-DAY B06</a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarCollapse" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Lumbung</a>
              <div class="dropdown-menu">
                <a href="/lumbung/readlumbung" class="dropdown-item">Lihat Isi Lumbung</a>
                <a href="/transaksiupgradelumbung/createtransaksiupgradelumbungpengguna" class="dropdown-item">Upgrade Lumbung</a>
                <a href="/transaksiupgradelumbung/readtransaksiupgradelumbungpengguna" class="dropdown-item">List Transaksi Upgrade Lumbung</a>
              </div>
            </li>
          </ul>
            <ul class="nav navbar-nav">
              <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Paket Koin</a>
                <div class="dropdown-menu">
                    <a href="/paketkoin/readpaketkoinpengguna" class="dropdown-item">List Paket Koin</a>
                    <a href="/transaksipembeliankoin/readtransaksipembeliankoinpengguna" class="dropdown-item">List Transaksi Pembelian Koin</a>
                </div>
              </li>
            </ul>
            <ul class="nav navbar-nav">
                <li class="nav-item dropdown">
                  <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Aset</a>
                  <div class="dropdown-menu">
                      <a href="/aset/listaset" class="dropdown-item">List Aset</a>
                      <a href="" class="dropdown-item">List Hewan Menghasilkan Produk Hewan</a>
                      <a href="" class="dropdown-item">List Bibit Menghasilkan Panen</a>
                  </div>
                </li>
            </ul>
            <ul class="nav navbar-nav">
              <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Koleksi Aset</a>
                <div class="dropdown-menu">
                    <a href="/koleksiaset/listkoleksi" class="dropdown-item">List Koleksi Aset</a>
                    <a href="/transaksipembelianaset/buattransaksi" class="dropdown-item">Buat Transaksi Pembelian Aset</a>
                    <a href="/transaksipembelianaset/listtransaksi" class="dropdown-item">List Transaksi Pembelian Aset</a>
                </div>
              </li>
          </ul>
          <ul class="nav navbar-nav">
            <li class="nav-item dropdown">
              <a href="/produk" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Produk</a>
              <div class="dropdown-menu">
                  <a href="/produk/listproduk" class="dropdown-item">List Produk</a>
                  <a href="/produk/listproduksi" class="dropdown-item">List Produksi</a>
              </div>
            </li>
          </ul>
          <ul class="nav navbar-nav">
            <li class="nav-item dropdown">
              <a href="/histori_produksi" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Proses Produksi</a>
              <div class="dropdown-menu">
                  <a href="" class="dropdown-item">Produksi Hewan</a>
                  <a href="" class="dropdown-item">List Histori Produksi Hewan</a>
                  <a href="/historitanaman/createhistoritanamanpengguna" class="dropdown-item">Produksi Tanaman</a>
                  <a href="/historitanaman/readhistoritanamanpengguna" class="dropdown-item">List Histori Produksi Tanaman</a>
                  <a href="/histori_produksi/produksiprodukmakanan" class="dropdown-item">Produksi Produk Makanan</a>
                  <a href="/histori_produksi/historiprodukmakanan" class="dropdown-item">List Histori Produksi Makanan</a>
              </div>
            </li>
          </ul>
          <ul class="nav navbar-nav">
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pesanan</a>
              <div class="dropdown-menu">
                  <a href="" class="dropdown-item">List Pesanan</a>
                  <a href="" class="dropdown-item">List Histori Penjualan</a>
              </div>
            </li>
          </ul>
            <ul class="nav navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Akun</a>
                    <div class="dropdown-menu dropdown-menu-end">
                        <a href="/home/logout" class="dropdown-item">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="mainbox container-fluid">
    {% block content %}

    {% endblock content %}
  </div>
  {% block scriptTambahan %}

{% endblock scriptTambahan %}
</body>

</html>

home/templates/home/homeAdmin.html
{% extends "home/baseAdmin.html" %}
{% load static %}

{% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <title>HI-DAY</title>
{% endblock head %}

{% block content %}
    <h1>Hello</h1>
    {% for res in result %}
    <p>Email :  {{ res.email }} </p> 
    {% endfor %}
{% endblock content %}

home/templates/home/homePengguna.html
{% extends "home/basePengguna.html" %}
{% load static %}

{% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <title>HI-DAY</title>
{% endblock head %}

{% block content %}
    <h1>Hello</h1>
    {% for res in result %}
    <p>Email :  {{ res.email }} </p>
    <p>Nama Area Pertanian : {{res.nama_area_pertanian}}</p>
    <p>XP: {{ res.xp }}</p>
    <p>Koin: {{ res.koin }}</p>
    <p>Level: {{ res.level }}</p>
    {% endfor %}
{% endblock content %}

home/templates/home/login.html
{% block meta %}
<style>
    #container {
        background-color: #AC3834;
        border-radius: 12px;
        position: relative;
        top: 100px;
        margin-left: auto;
        margin-right: auto;
        width: 25%;
        font-size: 20px;   
        text-align: center;
        margin-bottom: 48px;

    }

    #registerhead {
        font-size: 24px;
        color: white;
        background-color: #811112;
        height: 70px;
        text-align: center;
        border-top-left-radius: 12px;
        border-top-right-radius: 12px;

    }

    input[type=text], input[type=password] input[type=email] {
        width: 80%;
        padding: 15px;
        margin: 25px 0 22px 0;
        display: inline-block;
        border: none;
        background: #EDE0D0;
    }

    input[type=text]:focus, input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    #registerbody {
        font-size: 12px;
        text-align: center;
    }

    #submitbutton {
        background-color: #811112;
        color: white;
        padding: 16px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 25%;
        opacity: 0.9;
    }

    #submitbutton:hover {
        opacity: 1;
    }

    #loginbutton {
        padding: 16px 20px;
        color: #EDE0D0;
    }

</style>

<title>Login</title>
{% endblock meta %}

{% block content %}
<form method="POST" action="">
    <div id="container">
        {% csrf_token %}

        <div id="registerhead">
            <h5>FORM LOGIN</h5>
        </div>

        <div id="registerbody">
            <h2>Email</h2> 
            <p><input type="email" name="email"></p>
            <h2>Password</h2>
            <p><input type="password" name="password"></p>
        </div>

        <div id="registererror">
            {% for message in messages %}
            <p>{{message}}</p>
            {% endfor %}
        </div>
    
        <input type="submit" name="Create User" id="submitbutton" value="Login">
        <p id="loginbutton"> Don't have an account for Admin? <a href="{% url 'home:registeradmin' %}"> Register Admin</a></p>
        <p id="loginbutton"> Don't have an account for Pengguna? <a href="{% url 'home:registerpengguna' %}"> Register Pengguna</a></p>
    </div>
</form>
{% endblock content %}

home/templates/home/registerAdmin.html
{% block meta %}
<style>
    #container {
        background-color: #AC3834;
        border-radius: 12px;
        position: relative;
        top: 100px;
        margin-left: auto;
        margin-right: auto;
        width: 25%;
        font-size: 20px;   
        text-align: center;
        margin-bottom: 48px;

    }

    #registerhead {
        font-size: 24px;
        color: white;
        background-color: #811112;
        height: 70px;
        text-align: center;
        border-top-left-radius: 12px;
        border-top-right-radius: 12px;

    }

    input[type=text], input[type=password] {
        width: 80%;
        padding: 15px;
        margin: 25px 0 22px 0;
        display: inline-block;
        border: none;
        background: #EDE0D0;
    }

    input[type=text]:focus, input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    #registerbody {
        font-size: 12px;
        text-align: center;
    }

    #submitbutton {
        background-color: #811112;
        color: white;
        padding: 16px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 25%;
        opacity: 0.9;
        text-align: center;
    }

    #submitbutton:hover {
        opacity: 1;
    }

    #loginbutton {
        padding: 16px 20px;
        color: #EDE0D0;
    }

</style>

<title>Register Admin</title>
{% endblock meta %}

{% block content %}
<form method="POST" action="">
    <div id="container">
        {% csrf_token %}

        <div id="registerhead">
            <h5>FORM REGISTRASI ADMIN</h1>
        </div>

        <div id="registerbody">
            <h2>Email</h2> {{form.username}} <br>
            <h2>Password</h2>{{form.password2}} <br>
        </div>

        <div id="registererror">
            {% for message in messages %}
            <p>{{message}}</p>
            {% endfor %}
        </div>
    
        <input type="submit" name="Create User" id="submitbutton" value="Register">
        <p id="loginbutton"> Already have an account? <a href="{% url 'home:login' %}"> Login </a></p>
    </div>
</form>
{% endblock content %}

home/templates/home/registerPengguna.html
{% block meta %}
<style>
    #container {
        background-color: #AC3834;
        border-radius: 12px;
        position: relative;
        top: 100px;
        margin-left: auto;
        margin-right: auto;
        width: 25%;
        font-size: 20px;   
        text-align: center;
        margin-bottom: 48px;

    }

    #registerhead {
        font-size: 24px;
        color: white;
        background-color: #811112;
        height: 70px;
        text-align: center;
        border-top-left-radius: 12px;
        border-top-right-radius: 12px;

    }

    input[type=text], input[type=password] {
        width: 80%;
        padding: 15px;
        margin: 25px 0 22px 0;
        display: inline-block;
        border: none;
        background: #EDE0D0;
    }

    input[type=text]:focus, input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    #registerbody {
        font-size: 12px;
        text-align: center;
    }

    #submitbutton {
        background-color: #811112;
        color: white;
        padding: 16px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 25%;
        opacity: 0.9;
        text-align: center;
    }

    #submitbutton:hover {
        opacity: 1;
    }

    #loginbutton {
        padding: 16px 20px;
        color: #EDE0D0;
    }

</style>

<title>Register Pengguna</title>
{% endblock meta %}

{% block content %}
<form method="POST" action="">
    <div id="container">
        {% csrf_token %}

        <div id="registerhead">
            <h5>FORM REGISTRASI PENGGUNA</h1>
        </div>

        <div id="registerbody">
            <h2>Email</h2> {{form.username}} <br>
            <h2>Password</h2>{{form.password2}} <br>
            <h2>Nama Area Pertanian</h2>{{form.password}} <br>
        </div>

        <div id="registererror">
            {% for message in messages %}
            <p>{{message}}</p>
            {% endfor %}
        </div>
    
        <input type="submit" name="Create User" id="submitbutton" value="Register">
        <p id="loginbutton"> Already have an account? <a href="{% url 'home:login' %}"> Login </a></p>
    </div>
</form>
{% endblock content %}

home/templates/home/registeradmin.html
{% block meta %}
<style>
    #container {
        background-color: #AC3834;
        border-radius: 12px;
        position: relative;
        top: 100px;
        margin-left: auto;
        margin-right: auto;
        width: 25%;
        font-size: 20px;   
        text-align: center;
        margin-bottom: 48px;

    }

    #registerhead {
        font-size: 24px;
        color: white;
        background-color: #811112;
        height: 70px;
        text-align: center;
        border-top-left-radius: 12px;
        border-top-right-radius: 12px;

    }

    input[type=text], input[type=password] {
        width: 80%;
        padding: 15px;
        margin: 25px 0 22px 0;
        display: inline-block;
        border: none;
        background: #EDE0D0;
    }

    input[type=text]:focus, input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    #registerbody {
        font-size: 12px;
        text-align: center;
    }

    #submitbutton {
        background-color: #811112;
        color: white;
        padding: 16px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 25%;
        opacity: 0.9;
    }

    #submitbutton:hover {
        opacity: 1;
    }

    #loginbutton {
        padding: 16px 20px;
        color: #EDE0D0;
    }

</style>

<title>Register</title>
{% endblock meta %}

{% block content %}
<form method="POST" action="">
    <div id="container">
        {% csrf_token %}

        <div id="registerhead">
            <h5>FORM REGISTRASI ADMIN</h1>
        </div>

        <div id="registerbody">
            <h2>Email</h2> {{form.username}} <br>
            <h2>Password</h2>{{form.password}} <br>
        </div>

        <div id="registererror">
            {% for message in messages %}
            <p>{{message}}</p>
            {% endfor %}
        </div>
    
        <input type="submit" name="Create User" id="submitbutton">
        <p id="loginbutton"> Already have an account? <a href=""> Login </a></p>
    </div>
</form>
{% endblock content %}

home/templates/home/registerpengguna.html
{% block meta %}
<style>
    #container {
        background-color: #AC3834;
        border-radius: 12px;
        position: relative;
        top: 100px;
        margin-left: auto;
        margin-right: auto;
        width: 25%;
        font-size: 20px;   
        text-align: center;
        margin-bottom: 48px;

    }

    #registerhead {
        font-size: 24px;
        color: white;
        background-color: #811112;
        height: 70px;
        text-align: center;
        border-top-left-radius: 12px;
        border-top-right-radius: 12px;

    }

    input[type=text], input[type=password] {
        width: 80%;
        padding: 15px;
        margin: 25px 0 22px 0;
        display: inline-block;
        border: none;
        background: #EDE0D0;
    }

    input[type=text]:focus, input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    #registerbody {
        font-size: 12px;
        text-align: center;
    }

    #submitbutton {
        background-color: #811112;
        color: white;
        padding: 16px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 25%;
        opacity: 0.9;
    }

    #submitbutton:hover {
        opacity: 1;
    }

    #loginbutton {
        padding: 16px 20px;
        color: #EDE0D0;
    }

</style>

<title>Register</title>
{% endblock meta %}

{% block content %}
<form method="POST" action="">
    <div id="container">
        {% csrf_token %}

        <div id="registerhead">
            <h5>FORM REGISTRASI PENGGUNA</h1>
        </div>

        <div id="registerbody">
            <h2>Email</h2> {{form.username}} <br>
            <h2>Password</h2>{{form.password}} <br>
            <h2>Nama Area Pertanian</h2>{{form.username}} <br>
        </div>

        <div id="registererror">
            {% for message in messages %}
            <p>{{message}}</p>
            {% endfor %}
        </div>
    
        <input type="submit" name="Create User" id="submitbutton">
        <p id="loginbutton"> Already have an account? <a href=""> Login </a></p>
    </div>
</form>
{% endblock content %}