aset/urls.py
from django.urls import path

from .views import *

app_name = 'aset'

urlpatterns = [
    path('listaset', listaset, name='listaset'),
    path('buataset', buataset, name='buataset'),

    path('listaset_dekorasi', listaset_dekorasi, name='listaset_dekorasi'),
    path('listaset_bibittanaman', listaset_bibittanaman, name='listaset_bibittanaman'),
    path('listaset_kandang', listaset_kandang, name='listaset_kandang'),
    path('listaset_hewan', listaset_hewan, name='listaset_hewan'),
    path('listaset_alatproduksi', listaset_alatproduksi, name='listaset_alatproduksi'),
    path('listaset_petaksawah', listaset_petaksawah, name='listaset_petaksawah'),

    path('buatasetdekorasi', buatasetdekorasi, name='buasetasetdekorasi'),
    path('buatasetbibittanaman', buatasetbibittanaman, name='buatasetbibittanaman'),
    path('buatasetkandang', buatasetkandang, name='buatasetkandang'),
    path('buatasethewan', buatasethewan, name='buatasethewan'),
    path('buatasetalatproduksi', buatasetalatproduksi, name='buatasetalatproduksi'),
    path('buatasetpetaksawah', buatasetpetaksawah, name='buatasetpetaksawah')
]

hi_day_b06/urls.py
from django.contrib import admin
from login_register.views import login as index
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login_register/', include('login_register.urls')),
    path('home/', include('home.urls')),
    path('produk/', include('produk.urls')),
    path('histori_produksi/', include('histori_produksi.urls')),
    path('paketkoin/', include('paketkoin.urls')),
    path('transaksipembeliankoin/', include('transaksipembeliankoin.urls')),
    path('transaksiupgradelumbung/', include('transaksiupgradelumbung.urls')),
    path('lumbung/', include('lumbung.urls')),
    path('historitanaman/', include('historitanaman.urls')),
    path('aset/', include('aset.urls')),
    path('koleksiaset/', include('koleksiaset.urls')),
    path('transaksipembelianaset/', include('transaksipembelianaset.urls')),
    re_path(r'^$', index, name='index'),
]

login_register/urls.py
from django.urls import path

from .views import *

app_name = 'login_register'

urlpatterns = [
    path('login', login, name='login'),
    path('registeradmin', registeradmin, name='registeradmin'),
    path('registerpengguna', registerpengguna, name='registerpengguna'),
]

login_register/forms.py
from django.contrib.auth import forms
from django.forms import ModelForm, fields
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . import models 

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password2']

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = 'Email'
        self.fields['password2'].widget.attrs['placeholder'] = 'Password'

login_register/views.py
from django.shortcuts import render, redirect
from django.db import connection
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from django.db.utils import IntegrityError, InterfaceError
from .forms import *
from .forms2 import *
from .forms3 import *
from .loginForms import *

# Create your views here.
def login(request):
    MyForm = LoginForm(request.POST)
    cursor = connection.cursor();            
    cursor.execute("SET SEARCH_PATH TO hidayb06")
    # Form submission
    if (MyForm.is_valid() and request.method == 'POST'):
        
        # Define login form
        email = MyForm.cleaned_data['email']
        password = MyForm.cleaned_data['password']
        cursor.execute("SELECT email FROM akun WHERE email = %s", [email]) 
        result = cursor.fetchone()
        try :
            if(result == None): 
                return HttpResponseNotFound("The user does not exist")
                
            if(result is not None):
                cursor.execute("SELECT email from admin WHERE email = %s",[email])
                admin = cursor.fetchone()

                cursor.execute("SELECT email from pengguna WHERE email = %s",[email])
                pengguna = cursor.fetchone()
                
                #Assignment untuk mengetahui role user
                if(pengguna is not None):
                    role = "pengguna"
                    cursor.execute("SELECT email, password FROM pengguna WHERE email = %s AND password = %s", [email,password])
                    verif_akun = cursor.fetchone()
                elif (admin is not None):
                    role = "admin"
                    cursor.execute("SELECT email, password FROM admin WHERE email = %s AND password = %s", [email,password])
                    verif_akun = cursor.fetchone()
                if (verif_akun is not None):
                    cursor.execute("SET SEARCH_PATH TO public")
                    request.session['email'] = email
                    request.session['role'] = role
                    return redirect ("/home")
        except Exception as e:
            print(e)
            cursor.close()
        return redirect ("/login")

    else:
        cursor.execute("SET search_path TO public")
        return render(request, 'login_register/login.html', {'form' : MyForm})

def registeradmin(request):
    myForm = RegisterAdminForm(request.POST)
    cursor = connection.cursor()
    cursor.execute("SET SEARCH_PATH TO hidayb06")
    if (myForm.is_valid() and request.method == 'POST'):
        role = "admin"
        email = myForm.cleaned_data['email']
        password = myForm.cleaned_data['password']
        cursor.execute("SELECT EMAIL FROM ADMIN WHERE email = %s", [email]) 
        result = cursor.fetchone()
        if(result == None):
            try:
                cursor.execute("INSERT INTO AKUN VALUES (%s)", [email])
                cursor.execute("INSERT INTO ADMIN (email,password) VALUES (%s,%s)", [email,password])
                cursor.execute("SET SEARCH_PATH TO public")
                request.session['email'] = email
                request.session['role'] = role
                return redirect ("/home")
            except Exception as error:
                print(error)
        else:
                message = "User already exist"
                return render(request, 'login_register/registerAdmin.html', {'message':message})
    else :
        return render (request, 'login_register/registerAdmin.html', {'form':myForm})

def registerpengguna(request):
    myForm = RegisterPenggunaForm(request.POST)
    cursor = connection.cursor()
    cursor.execute("SET SEARCH_PATH TO hidayb06")
    if (myForm.is_valid() and request.method == 'POST'):
        role = "pengguna"
        email = myForm.cleaned_data['email']
        password = myForm.cleaned_data['password']
        nama_area_pertanian = myForm.cleaned_data['nama_area_pertanian']
        cursor.execute("SELECT EMAIL FROM PENGGUNA WHERE email = %s", [email]) 
        result = cursor.fetchone()
        if(result == None):
            try:
                cursor.execute("INSERT INTO AKUN VALUES (%s)", [email])
                cursor.execute("INSERT INTO PENGGUNA (email,password,nama_area_pertanian) VALUES (%s,%s,%s)", [email, password, nama_area_pertanian])
                cursor.execute("SET SEARCH_PATH TO public")
                request.session['email'] = email
                request.session['role'] = role
                return redirect ("/home")
            except Exception as error:
                print(error)
        else:
                message = "User already exist"
                return render(request, 'login_register/registerPengguna.html', {'message':message})
    else :
        return render (request, 'login_register/registerPengguna.html', {'form':myForm})

login_register/templates/login_register/login.html
{% block meta %}
<style>
    #container {
        background-color: #AC3834;
        border-radius: 12px;
        position: relative;
        top: 100px;
        margin-left: auto;
        margin-right: auto;
        width: 25%;
        font-size: 20px;   
        text-align: center;
        margin-bottom: 48px;

    }

    #registerhead {
        font-size: 24px;
        color: white;
        background-color: #811112;
        height: 70px;
        text-align: center;
        border-top-left-radius: 12px;
        border-top-right-radius: 12px;

    }

    input[type=text], input[type=password] input[type=email] {
        width: 80%;
        padding: 15px;
        margin: 25px 0 22px 0;
        display: inline-block;
        border: none;
        background: #EDE0D0;
    }

    input[type=text]:focus, input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    #registerbody {
        font-size: 12px;
        text-align: center;
    }

    #submitbutton {
        background-color: #811112;
        color: white;
        padding: 16px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 25%;
        opacity: 0.9;
    }

    #submitbutton:hover {
        opacity: 1;
    }

    #loginbutton {
        padding: 16px 20px;
        color: #EDE0D0;
    }

</style>

<title>Login</title>
{% endblock meta %}

{% block content %}
<form method="POST" action="">
    <div id="container">
        {% csrf_token %}

        <div id="registerhead">
            <h5>FORM LOGIN</h5>
        </div>

        <div id="registerbody">
            <h2>Email</h2> 
            <p><input type="email" name="email"></p>
            <h2>Password</h2>
            <p><input type="password" name="password"></p>
        </div>

        <div id="registererror">
            {% for message in messages %}
            <p>{{message}}</p>
            {% endfor %}
        </div>
    
        <input type="submit" name="Create User" id="submitbutton" value="Login">
        <p id="loginbutton"> Don't have an account for Admin? <a href="{% url 'login_register:registeradmin' %}"> Register Admin</a></p>
        <p id="loginbutton"> Don't have an account for Pengguna? <a href="{% url 'login_register:registerpengguna' %}"> Register Pengguna</a></p>
    </div>
</form>
{% endblock content %}

login_register/templates/login_register/registerAdmin.html
{% block meta %}
<style>
    #container {
        background-color: #AC3834;
        border-radius: 12px;
        position: relative;
        top: 100px;
        margin-left: auto;
        margin-right: auto;
        width: 25%;
        font-size: 20px;   
        text-align: center;
        margin-bottom: 48px;

    }

    #registerhead {
        font-size: 24px;
        color: white;
        background-color: #811112;
        height: 70px;
        text-align: center;
        border-top-left-radius: 12px;
        border-top-right-radius: 12px;

    }

    input[type=text] {
        width: 80%;
        padding: 15px;
        margin: 25px 0 22px 0;
        display: inline-block;
        border: none;
        background: #EDE0D0;
    }

    input[type=text]:focus, input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    #registerbody {
        font-size: 12px;
        text-align: center;
    }

    #submitbutton {
        background-color: #811112;
        color: white;
        padding: 16px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 25%;
        opacity: 0.9;
        text-align: center;
    }

    #submitbutton:hover {
        opacity: 1;
    }

    #loginbutton {
        padding: 16px 20px;
        color: #EDE0D0;
    }

</style>

<title>Register Admin</title>
{% endblock meta %}

{% block content %}
<form method="POST" action="">
    <div id="container">
        {% csrf_token %}

        <div id="registerhead">
            <h5>FORM REGISTRASI ADMIN</h1>
        </div>

        <div id="registerbody">
            <h2>Email</h2>
            <p><input type="email" name="email"></p>
            <h2>Password</h2>
            <p><input type="password" name="password"></p>
            
        </div>

        <div id="registererror">
            {% for message in messages %}
            <p>{{message}}</p>
            {% endfor %}
        </div>
        <button type = "submit" value = "submit">Submit</button>
        <p id="loginbutton"> Already have an account? <a href="{% url 'login_register:login' %}"> Login </a></p>
    </div>
</form>
{% endblock content %}

login_register/templates/login_register/registerPengguna.html
{% block meta %}
<style>
    #container {
        background-color: #AC3834;
        border-radius: 12px;
        position: relative;
        top: 100px;
        margin-left: auto;
        margin-right: auto;
        width: 25%;
        font-size: 20px;   
        text-align: center;
        margin-bottom: 48px;

    }

    #registerhead {
        font-size: 24px;
        color: white;
        background-color: #811112;
        height: 70px;
        text-align: center;
        border-top-left-radius: 12px;
        border-top-right-radius: 12px;

    }

    input[type=text] {
        width: 80%;
        padding: 15px;
        margin: 25px 0 22px 0;
        display: inline-block;
        border: none;
        background: #EDE0D0;
    }

    input[type=text]:focus, input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    #registerbody {
        font-size: 12px;
        text-align: center;
    }

    #submitbutton {
        background-color: #811112;
        color: white;
        padding: 16px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 25%;
        opacity: 0.9;
        text-align: center;
    }

    #submitbutton:hover {
        opacity: 1;
    }

    #loginbutton {
        padding: 16px 20px;
        color: #EDE0D0;
    }

</style>

<title>Register Pengguna</title>
{% endblock meta %}

{% block content %}
<form method="POST" action="">
    <div id="container">
        {% csrf_token %}

        <div id="registerhead">
            <h5>FORM REGISTRASI PENGGUNA</h1>
        </div>

        <div id="registerbody">
            <h2>Email</h2>
            <p><input type="email" name="email"></p>
            <h2>Password</h2>
            <p><input type="password" name="password"></p>
            <h2>Nama Area Pertanian</h2>
            <p><input type="nama_area_pertanian" name="nama_area_pertanian"></p>
        </div>

        <div id="registererror">
            {% for message in messages %}
            <p>{{message}}</p>
            {% endfor %}
        </div>
    
        <input type="submit" name="Create User" id="submitbutton" value="Register">
        <p id="loginbutton"> Already have an account? <a href="{% url 'login_register:login' %}"> Login </a></p>
    </div>
</form>
{% endblock content %}