aset/urls.py
from django.urls import path

from .views import *

app_name = 'aset'

urlpatterns = [
    path('listaset', listaset, name='listaset'),
    path('buataset', buataset, name='buataset'),

    path('listaset_dekorasi', listaset_dekorasi, name='listaset_dekorasi'),
    path('listaset_bibittanaman', listaset_bibittanaman, name='listaset_bibittanaman'),
    path('listaset_kandang', listaset_kandang, name='listaset_kandang'),
    path('listaset_hewan', listaset_hewan, name='listaset_hewan'),
    path('listaset_alatproduksi', listaset_alatproduksi, name='listaset_alatproduksi'),
    path('listaset_petaksawah', listaset_petaksawah, name='listaset_petaksawah'),

    path('buatasetdekorasi', buatasetdekorasi, name='buasetasetdekorasi'),
    path('buatasetbibittanaman', buatasetbibittanaman, name='buatasetbibittanaman'),
    path('buatasetkandang', buatasetkandang, name='buatasetkandang'),
    path('buatasethewan', buatasethewan, name='buatasethewan'),
    path('buatasetalatproduksi', buatasetalatproduksi, name='buatasetalatproduksi'),
    path('buatasetpetaksawah', buatasetpetaksawah, name='buatasetpetaksawah')
]

hi_day_b06/urls.py
from django.contrib import admin
from login_register.views import login as index
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login_register/', include('login_register.urls')),
    path('home/', include('home.urls')),
    path('produk/', include('produk.urls')),
    path('histori_produksi/', include('histori_produksi.urls')),
    path('paketkoin/', include('paketkoin.urls')),
    path('transaksipembeliankoin/', include('transaksipembeliankoin.urls')),
    path('transaksiupgradelumbung/', include('transaksiupgradelumbung.urls')),
    path('lumbung/', include('lumbung.urls')),
    path('historitanaman/', include('historitanaman.urls')),
    path('aset/', include('aset.urls')),
    path('koleksiaset/', include('koleksiaset.urls')),
    path('transaksipembelianaset/', include('transaksipembelianaset.urls')),
    re_path(r'^$', index, name='index'),
]

transaksiupgradelumbung/urls.py
from django.urls import path

from .views import *
from home.views import home

app_name = 'transaksiupgradelumbung'

urlpatterns = [
    path('home', home, name='home'),
    path('createtransaksiupgradelumbungpengguna', createtransaksiupgradelumbungpengguna, name='createtransaksiupgradelumbungpengguna'),
    path('readtransaksiupgradelumbungadmin', readtransaksiupgradelumbungadmin, name='readtransaksiupgradelumbungadmin'),
    path('readtransaksiupgradelumbungpengguna', readtransaksiupgradelumbungpengguna, name='readtransaksiupgradelumbungpengguna'),
]

transaksiupgradelumbung/forms.py
from django.contrib.auth import forms
from django.forms import ModelForm, fields
from django import forms
from django.utils import timezone
from django.db import models
import datetime
from django.db.models.deletion import DO_NOTHING
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
# from . import models 

class CreateTransaksiUpgradeLumbungPenggunaForm(forms.Form):
    level_lumbung = forms.CharField(label='Level Lumbung')
    kapasitas_lumbung = forms.CharField(label='Kapasitas Lumbung')
    biaya_upgrade = forms.CharField(label='Biaya Upgrade')
    waktu_upgrade = models.DateTimeField(auto_now_add=True)

transaksiupgradelumbung/views.py
import email
from collections import namedtuple
import imp
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.db import connection
from django.db.utils import IntegrityError, InterfaceError
from .forms import *
from django.utils import timezone

# Create your views here.
def namedtuplefetchall(cursor):
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def createtransaksiupgradelumbungpengguna(request):
    # form = CreateTransaksiUpgradeLumbungPenggunaForm(request.POST or None)
    cursor = connection.cursor()
    cursor.execute("SET search_path TO public")
    userEmail = request.session['email']
    cursor.execute("SET SEARCH_PATH TO hidayb06")
    cursor.execute("SELECT * FROM LUMBUNG WHERE LUMBUNG.EMAIL = %s", [userEmail])
    result = cursor.fetchall()
    level = (result[0])[1]
    kapasitas = (result[0])[2]
    now = timezone.now()
    if (request.method == 'POST'):
        # waktu = form.cleaned_data['waktu_upgrade']
        # level = form.cleaned_data['level_lumbung']
        # kapasitas = form.cleaned_data['kapasitas_lumbung']
        # biaya = form.cleaned_data['biaya_upgrade']
        try:
            cursor.execute("INSERT INTO TRANSAKSI_UPGRADE_LUMBUNG (email,waktu) VALUES (%s,%s)", [userEmail,now])
            cursor.execute("UPDATE LUMBUNG SET LEVEL = LEVEL + 1, KAPASITAS_MAKSIMAL = KAPASITAS_MAKSIMAL + 50 WHERE EMAIL = %s", [userEmail])
            cursor.execute("SET SEARCH_PATH TO public")
            return redirect("/transaksiupgradelumbung/readtransaksiupgradelumbungpengguna")
        except Exception as error:
            print(error)
    else:
        return render(request, 'transaksiupgradelumbung/createTransaksiUpgradeLumbungPengguna.html', {'level':level, 'kapasitas':kapasitas})

def readtransaksiupgradelumbungadmin(request):
    cursor = connection.cursor()
    cursor.execute("SET search_path TO public")
    role = request.session ['role']
    userEmail = request.session['email']
    if (role == "admin"):
        try:
            cursor.execute("SET SEARCH_PATH TO hidayb06")
            cursor.execute("""SELECT EMAIL, WAKTU FROM TRANSAKSI_UPGRADE_LUMBUNG WHERE TRANSAKSI_UPGRADE_LUMBUNG.EMAIL IN (SELECT PENGGUNA.EMAIL FROM PENGGUNA);""")
            result = namedtuplefetchall(cursor)
        except Exception as e:
            print(e)

        return render(request, 'transaksiupgradelumbung/readTransaksiUpgradeLumbungAdmin.html', {'result':result})

def readtransaksiupgradelumbungpengguna(request):
    cursor = connection.cursor()
    cursor.execute("SET search_path TO public")
    role = request.session ['role']
    userEmail = request.session['email']
    if (role == "pengguna"):
        try:
            cursor.execute("SET SEARCH_PATH TO hidayb06")
            cursor.execute("""SELECT WAKTU FROM TRANSAKSI_UPGRADE_LUMBUNG WHERE EMAIL = %s;""", [userEmail])
            result = namedtuplefetchall(cursor)
        except Exception as e:
            print(e)

        return render(request, 'transaksiupgradelumbung/readTransaksiUpgradeLumbungPengguna.html', {'result':result})

transaksiupgradelumbung/templates/transaksiupgradelumbung/createTransaksiUpgradeLumbungPengguna.html
{% extends "home/basePengguna.html" %}
{% load static %}

{% block head %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>Create Transaksi Upgrade Lumbung (Pengguna)</title>
{% endblock head %}

{% block content %}

<form method="POST">
  {% csrf_token %}
<h1>UPGRADE LUMBUNG (PENGGUNA)</h1>
<p>Level Lumbung</p>
<p style="font-weight:bold ;">{{level}} -> {{level}} + 1</p>
<p>Kapasitas Lumbung</p>
<p style="font-weight:bold ;">{{kapasitas}} -> {{kapasitas}} + 50</p>
<p>Biaya Upgrade</p>
<p style="font-weight:bold ;">200</p>
<br>
<p style="color: red;">{{ message }}</p>
<input type = "submit" value = "submit"/>
<p><a href="{% url 'transaksiupgradelumbung:readtransaksiupgradelumbungpengguna' %}">Cancel</a></p>

</form>

{% endblock content %}

transaksiupgradelumbung/templates/transaksiupgradelumbung/readTransaksiUpgradeLumbungAdmin.html
{% extends "home/baseAdmin.html" %}
{% load static %}

{% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Read Transaksi Upgrade Lumbung (Admin)</title>
{% endblock head %}
    
{% block content %}
<div class="container-md">
    <div class="d-grip gap-3">
        <div class="p-2 bg-light border">
            <div class="mx-auto" style="width: 500px;">
                <h1>List Transaksi Upgrade Lumbung (Admin)</h1>
            </div>
        </div>
        <div class="p-2 bg-light border">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col"><b>No</b></th>
                        <th scope="col"><b>Email Pengguna</b></th>
                        <th scope="col"><b>Waktu Upgrade</b></th>
                    </tr>
                </thead>
                <tbody>
                    {% for res in result %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ res.email }}</td>
                        <td>{{ res.waktu }}</td>
                    </tr>
                    {% endfor %}
                  <tr>
                  </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

transaksiupgradelumbung/templates/transaksiupgradelumbung/readTransaksiUpgradeLumbungPengguna.html
{% extends "home/basePengguna.html" %}
{% load static %}

{% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Read Transaksi Upgrade Lumbung (Pengguna)</title>
{% endblock head %}
    
{% block content %}
<div class="container-md">
    <div class="d-grip gap-3">
        <div class="p-2 bg-light border">
            <div class="mx-auto" style="width: 500px;">
                <h1>List Transaksi Upgrade Lumbung (Pengguna)</h1>
            </div>
        </div>
        <div class="p-2 bg-light border">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col"><b>No</b></th>
                        <th scope="col"><b>Waktu Upgrade</b></th>
                    </tr>
                </thead>
                <tbody>
                    {% for res in result %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ res.waktu }}</td>
                    </tr>
                    {% endfor %}
                  <tr>
                  </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}